install-or-update-macports.sh: add setuptools to needed ports
no longer installed by default with python 3.12+
required for mesa to build

fixes:

Running command: /opt/buildX11/bin/python3 -c '
from distutils.version import StrictVersion
import mako
assert StrictVersion(mako.__version__) > StrictVersion("0.8.0")
  '
--- stdout ---

--- stderr ---
Traceback (most recent call last):
  File "<string>", line 2, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'

meson.build:1018:2: ERROR: Problem encountered: Python (3.x) mako module >= 0.8.0 required to build mesa.